#cloud-config

package_update: true

packages:
 - snap
 
runcmd:
 - [ sh, -c, echo "=========hello world'=========" ]
 - apt update --fix-missing
 - snap refresh
 - snap install microk8s
 - microk8s status --wait-ready
 - microk8s enable dns ingress' > cloud-config-microk8s.yaml
 - sudo usermod -a -G microk8s multipass
 - /snap/bin/microk8s.config > kubeconfig
 - microk8s kubectl --kubeconfig=kubeconfig get all --all-namespaces
